### ISSUE TITLE
DICOM Images are not being put on HealthImaging

### ISSUE THREAD

**Issue by RonakKanji** [aws-samples/aws-healthimaging-samples#53]
The project was successfully deployed, and after running a local EC2 instance to send the dicom imeages, the images are uploaded to s3 bucket successfully and the metadata is visible in the RDS table. However in HealthImaging the dicom data is not getting stored, nor are the rds ahli tables populated.

**Comment by yyao84** [comment]
Hi @RonakKanji - is the project you're using, `dicom-ingestion-to-s3-healthimaging`?

**Comment by RonakKanji** [comment]
Hi, yes I am using the project `dicom-ingestion-to-s3-healthimaging`.

I realized the SQS Queue `iep-01-EDGE_DEVICE_inbound.fifo` was unable to trigger. After debugging it, I could find the code there the SQS Queue was being triggered but I was unsure so as to why it was unable to trigger even after giving the necessary  permissions. 

So then I had sent the message to the SQS Queue from the Lambda function which handles the operation of migrating the DICOM images to the result directory in S3 Bucket.
After doing that, the project started to work successfully.

**Comment by awsjpleger** [comment]
Hi RonakKanji.
I'm the author of this project, sorry I could not catch up with you sooner. Glad it got resolved. Let me know if you need more support. Also, I would suggest you have a look to the metadata-index project in the same repository. You can combine the dicom-ingestion project and the metadata-index project to end up with DICOM ingestion and a nicer database index of the AHI datastore content.
