### ISSUE TITLE
Recreating DICOM compatible data from AWS Health Imaging service.

### ISSUE THREAD

**Issue by SunilCarmel** [aws-samples/aws-healthimaging-samples#57]
Hi,

We are exploring the capabilities of Health Imaging Service for consuming it for one of our use case.

Use case:  
 1) Import the DICOM data from On-premise to Health Imaging.
 2) Apply some AI/ML algorithms over the data set(using sage maker or something).
 3)  Use the inference result to create a new Image data set based out of the original data set by adding some annotations , color mapping etc.
4) Now I want to store the processed data set back to On premise PACS or to show in a Standard DICOM Viewer deployed locally.

For implementing the 4th step following tasks are expecting.

1) Retrieve newly created data set as meta data and Image data using Health Imaging APIs.
2) Uncompress the image data.
3) Re-create the DCM format data using the meta data and uncompressed pixel data.
4) Push to PACS using C-STORE/STOW DICOM communication.
 
But I am not seeing any sample implementation for the same among the given examples. 
Is it not a recommended use case  for Health Imaging Service?

Or

Is there any recommended way for doing this?
What deployment modes are preferable for achieving  low latency and high performance? 
I am mostly concerning about the time taken for uncompressing and re-stitching the DCM files.

Looking forward to your thoughts on this.

**Comment by chafey** [comment]
Hello - we have an AWS Sample python library that will create DICOM P10 from AHI in another repo here: https://github.com/aws-samples/healthlake-imaging-to-dicom-python-module.

**Comment by chafey** [comment]
Looks resolved to closing
