### ISSUE TITLE
Coloured DICOM Images are not showing correctly

### ISSUE THREAD

**Issue by graftedscion** [aws-samples/aws-healthimaging-samples#58]
![image (2)](https://github.com/aws-samples/aws-healthimaging-samples/assets/159879694/a5ea4a86-fbea-4c07-a585-601342fa5242)
![image (1)](https://github.com/aws-samples/aws-healthimaging-samples/assets/159879694/8b684c07-4c51-4963-b756-1abab4eb9a37)

I have tried a colored but it seems to be not showing up correctly, have attached original image along with image viewed on the Viewer for your reference.

-SK

**Comment by graftedscion** [comment]
any update on this? @yyao84

**Comment by yyao84** [comment]
I am looking at this now @graftedscion and will have an update for you this week

**Comment by yyao84** [comment]
@graftedscion - I pushed some updates to the UI code - can you update your build and see if the images are viewable? It handles RGB images but does not yet handle palette color ones

**Comment by graftedscion** [comment]
@yyao84 RBG Images are now visible.
