### ISSUE TITLE
How to restart TLM proxy

### ISSUE THREAD

**Issue by terry-wilson** [aws-samples/aws-healthimaging-samples#67]
@yyao84 I have been playing around with the TLM proxy and for the most part it has been working great, however, I did run into a problem the other day where it seemed to randomly not respond to requests. Given that it had been working fine, I figured I would just try to restart it but was not exactly sure how I should do that. I played around with the services in the AWS console and eventually was able to get new instances running after trying a number of different things ... sure enough the TLM proxy started working fine again after this restart. However, assuming I am going to need to do this again at some point, I am  hoping to understand the "proper" way to restart the TLM proxy?

**Comment by yyao84** [comment]
Hi @terry-wilson - the easiest way is to force a new deployment, which starts up new containers, drains connections from the old containers and then shuts them down.

In the console:
* Navigate to [ECS](https://console.aws.amazon.com/ecs/v2/clusters) (double check the region, it takes me to a random region half the time if I don't have a preferred one set in my settings)
* Select the `TileLevelMarkerProxyStack-ecscluster` cluster
* Select the `TileLevelMarkerProxyStack-ecsfargateservice` service
* Select the `Update service` button
* In the `Deployment configuration` section, check `Force new deployment`
* Select `Update`
* This takes you to the `Deployments` tab for the service, where it shows you the status of the new deployment

To use the CLI:
`aws ecs update-service --cluster ${cluster_name} --service ${service_name} --force-new-deployment`

I've also seen issues with the TLM proxy, and am working on an update for it to not use Elasticache but rather sit behind CloudFront.
